# This file provides instructions for packaging.

`MooseX-DeclareX-More`
	perl_version_from m`MooseX::DeclareX::More`;
	version_from      m`MooseX::DeclareX::More`;
	readme_from       m`MooseX::DeclareX::More`;
	test_requires     p`Test::More 0.61`  .

