# This file provides instructions for packaging.

`MooseX-DeclareX`
	perl_version_from m`MooseX::DeclareX`;
	version_from      m`MooseX::DeclareX`;
	readme_from       m`MooseX::DeclareX`;
	test_requires     p`Test::More 0.61`  .

